-- =============================================================================
-- 02_raw_tables.sql
-- Purpose : Create the RAW tables and load the three source files into them,
--           then check row counts and log the run.
-- Owner   : Data Engineer (Shubham)
-- Why all VARCHAR: RAW keeps data exactly as received, so nothing is lost or
--           mis-typed on load (e.g. leading zeros, odd date formats). Typing and
--           cleaning happen in STAGING.
-- Prerequisites:
--           1. sql/01_setup.sql has been run (RAW.FF_CSV, RAW.LANDING exist).
--           2. The 3 files from data/clean/ are uploaded to @RAW.LANDING:
--              charities_organisations.csv, companies_office.csv, ird_donee.csv
-- Inputs  : @RAW.LANDING/*.csv
-- Outputs : RAW.CHARITIES_ORGANISATIONS, RAW.COMPANIES_OFFICE, RAW.IRD_DONEE,
--           one row in AUDIT.PIPELINE_RUN (step '02_raw').
-- Notes   : Idempotent. CREATE OR REPLACE gives each table fresh COPY load
--           history, so a re-run reloads the files instead of skipping them.
-- =============================================================================
-- Note: the source CSV quotes every field, so blank values load as '' (empty string), not NULL. RAW keeps them as received; STAGING converts them with NULLIF(TRIM(col), '').

USE DATABASE KENDRIX;

-- 1) Charities Register: 81 source columns, all VARCHAR
CREATE OR REPLACE TABLE RAW.CHARITIES_ORGANISATIONS (
    ORGANISATIONID VARCHAR,
    ACCOUNTID VARCHAR,
    NAME VARCHAR,
    CHARITYREGISTRATIONNUMBER VARCHAR,
    WEBSITEURL VARCHAR,
    EMAILADDRESS1 VARCHAR,
    TELEPHONE1 VARCHAR,
    TELEPHONE2 VARCHAR,
    TELEPHONEDAY VARCHAR,
    FAX VARCHAR,
    POSTALADDRESSCITY VARCHAR,
    POSTALADDRESSCOUNTRY VARCHAR,
    POSTALADDRESSLINE1 VARCHAR,
    POSTALADDRESSLINE2 VARCHAR,
    POSTALADDRESSPOSTCODE VARCHAR,
    POSTALADDRESSSUBURB VARCHAR,
    STREETADDRESSCITY VARCHAR,
    STREETADDRESSCOUNTRY VARCHAR,
    STREETADDRESSLINE1 VARCHAR,
    STREETADDRESSLINE2 VARCHAR,
    STREETADDRESSPOSTCODE VARCHAR,
    STREETADDRESSSUBURB VARCHAR,
    CHARITYEMAILADDRESS VARCHAR,
    COMPANIESOFFICENUMBER VARCHAR,
    DATEREGISTERED VARCHAR,
    DEREGISTRATIONDATE VARCHAR,
    ENDOFYEARDAYOFMONTH VARCHAR,
    ENDOFYEARMONTH VARCHAR,
    ESTABLISHEDBYPARLIAMENTACT VARCHAR,
    EXCEMPTIONCOMMENT VARCHAR,
    ISINCORPORATED VARCHAR,
    MAORITRUSTBOARD VARCHAR,
    MAORITRUSTAPPROVED VARCHAR,
    MARAEFUNDS VARCHAR,
    MARAERESERVATION VARCHAR,
    NOTICES VARCHAR,
    ONLANDUNDERTETUREWHENUAMAORIACT VARCHAR,
    ORGANISATIONALTYPE VARCHAR,
    PERCENTAGESPENTOVERSEAS VARCHAR,
    REGISTRATIONSTATUS VARCHAR,
    SOCIETYINSTITUTION VARCHAR,
    TRUSTEESTRUST VARCHAR,
    EXEMPTIONS VARCHAR,
    ANNUALRETURNDUEDATE VARCHAR,
    ANNUALRETURNEXTENSIONDATE VARCHAR,
    GROUPTYPE VARCHAR,
    GROUPID VARCHAR,
    MAINACTIVITYID VARCHAR,
    MAINBENEFICIARYID VARCHAR,
    MAINSECTORID VARCHAR,
    OTHERNAMES VARCHAR,
    MODIFIEDON VARCHAR,
    NZBNNUMBER VARCHAR,
    DEREGISTRATIONREASONS VARCHAR,
    CHARITABLEPURPOSE VARCHAR,
    ENTITYSTRUCTURE VARCHAR,
    FACEBOOKNAME VARCHAR,
    TWITTERNAME VARCHAR,
    SOCIALNETWORKNAME VARCHAR,
    CONTROLLEDBYNAME VARCHAR,
    DEREGISTRATIONREASONNEW VARCHAR,
    OVERSEASOPERATIONAFRICA VARCHAR,
    OVERSEASOPERATIONANTARCTICA VARCHAR,
    OVERSEASOPERATIONASIA VARCHAR,
    ORGANISATIONRECEIVESDONATIONSKOHA VARCHAR,
    ETHNICCHARITY VARCHAR,
    OVERSEASOPERATIONEUROPE VARCHAR,
    ORGANISATIONGENERATESFUNDSGRANTSDONATIONSTOOTHERS VARCHAR,
    KAUPAPAMAORICHARITYAFFILIATIONWITHIWIANDORHAPU VARCHAR,
    KAUPAPAMAORICHARITY VARCHAR,
    KAUPAPAMAORICHARITYMARAE VARCHAR,
    OVERSEASOPERATIONNORTHAMERICA VARCHAR,
    OVERSEASOPERATIONOCEANIA VARCHAR,
    OPERATEOVERSEAS VARCHAR,
    OTHERLEGALSTRUCTURE VARCHAR,
    KAUPAPAMAORICHARITYOWNERSHIP VARCHAR,
    PASIFIKACHARITY VARCHAR,
    PURPOSETOGIVEGRANTSANDDONATIONS VARCHAR,
    OVERSEASOPERATIONSOUTHAMERICA VARCHAR,
    KAUPAPAMAORICHARITYFOCUSESONOUTCOMESFORMAORI VARCHAR,
    LEGALSTRUCTURE VARCHAR,
    _SOURCE_FILE VARCHAR,
    _LOADED_AT TIMESTAMP_NTZ
);

COPY INTO RAW.CHARITIES_ORGANISATIONS (ORGANISATIONID, ACCOUNTID, NAME, CHARITYREGISTRATIONNUMBER, WEBSITEURL, EMAILADDRESS1, TELEPHONE1, TELEPHONE2, TELEPHONEDAY, FAX, POSTALADDRESSCITY, POSTALADDRESSCOUNTRY, POSTALADDRESSLINE1, POSTALADDRESSLINE2, POSTALADDRESSPOSTCODE, POSTALADDRESSSUBURB, STREETADDRESSCITY, STREETADDRESSCOUNTRY, STREETADDRESSLINE1, STREETADDRESSLINE2, STREETADDRESSPOSTCODE, STREETADDRESSSUBURB, CHARITYEMAILADDRESS, COMPANIESOFFICENUMBER, DATEREGISTERED, DEREGISTRATIONDATE, ENDOFYEARDAYOFMONTH, ENDOFYEARMONTH, ESTABLISHEDBYPARLIAMENTACT, EXCEMPTIONCOMMENT, ISINCORPORATED, MAORITRUSTBOARD, MAORITRUSTAPPROVED, MARAEFUNDS, MARAERESERVATION, NOTICES, ONLANDUNDERTETUREWHENUAMAORIACT, ORGANISATIONALTYPE, PERCENTAGESPENTOVERSEAS, REGISTRATIONSTATUS, SOCIETYINSTITUTION, TRUSTEESTRUST, EXEMPTIONS, ANNUALRETURNDUEDATE, ANNUALRETURNEXTENSIONDATE, GROUPTYPE, GROUPID, MAINACTIVITYID, MAINBENEFICIARYID, MAINSECTORID, OTHERNAMES, MODIFIEDON, NZBNNUMBER, DEREGISTRATIONREASONS, CHARITABLEPURPOSE, ENTITYSTRUCTURE, FACEBOOKNAME, TWITTERNAME, SOCIALNETWORKNAME, CONTROLLEDBYNAME, DEREGISTRATIONREASONNEW, OVERSEASOPERATIONAFRICA, OVERSEASOPERATIONANTARCTICA, OVERSEASOPERATIONASIA, ORGANISATIONRECEIVESDONATIONSKOHA, ETHNICCHARITY, OVERSEASOPERATIONEUROPE, ORGANISATIONGENERATESFUNDSGRANTSDONATIONSTOOTHERS, KAUPAPAMAORICHARITYAFFILIATIONWITHIWIANDORHAPU, KAUPAPAMAORICHARITY, KAUPAPAMAORICHARITYMARAE, OVERSEASOPERATIONNORTHAMERICA, OVERSEASOPERATIONOCEANIA, OPERATEOVERSEAS, OTHERLEGALSTRUCTURE, KAUPAPAMAORICHARITYOWNERSHIP, PASIFIKACHARITY, PURPOSETOGIVEGRANTSANDDONATIONS, OVERSEASOPERATIONSOUTHAMERICA, KAUPAPAMAORICHARITYFOCUSESONOUTCOMESFORMAORI, LEGALSTRUCTURE, _SOURCE_FILE, _LOADED_AT)
FROM (
  SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59, $60, $61, $62, $63, $64, $65, $66, $67, $68, $69, $70, $71, $72, $73, $74, $75, $76, $77, $78, $79, $80, $81,
         METADATA$FILENAME, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
  FROM @RAW.LANDING/charities_organisations.csv
)
FILE_FORMAT = (FORMAT_NAME = 'RAW.FF_CSV')
ON_ERROR = ABORT_STATEMENT;

-- 2) Companies Office exports
CREATE OR REPLACE TABLE RAW.COMPANIES_OFFICE (
    BUSINESS_NAME VARCHAR, NZBN VARCHAR, REGISTRATION_DATE VARCHAR, ENTITY_TYPE VARCHAR,
    ACT VARCHAR, TRADING_AS VARCHAR, PHYSICAL_ADDRESS VARCHAR, PREVIOUSLY_KNOWN_AS VARCHAR,
    PREVIOUSLY_TRADING_AS VARCHAR, STATUS VARCHAR, STATUS_DATE VARCHAR, EXPORT_FILE VARCHAR,
    _SOURCE_FILE VARCHAR, _LOADED_AT TIMESTAMP_NTZ
);

COPY INTO RAW.COMPANIES_OFFICE
FROM (
  SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,
         METADATA$FILENAME, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
  FROM @RAW.LANDING/companies_office.csv
)
FILE_FORMAT = (FORMAT_NAME = 'RAW.FF_CSV')
ON_ERROR = ABORT_STATEMENT;

-- 3) IRD donee list (optional source)
CREATE OR REPLACE TABLE RAW.IRD_DONEE (
    ORGANISATION_NAME VARCHAR, CEASED_AS_DONEE VARCHAR,
    _SOURCE_FILE VARCHAR, _LOADED_AT TIMESTAMP_NTZ
);

COPY INTO RAW.IRD_DONEE
FROM (
  SELECT $1,$2, METADATA$FILENAME, CURRENT_TIMESTAMP()::TIMESTAMP_NTZ
  FROM @RAW.LANDING/ird_donee.csv
)
FILE_FORMAT = (FORMAT_NAME = 'RAW.FF_CSV')
ON_ERROR = ABORT_STATEMENT;

-- 4) Audit log row (STATUS is FAIL if any count is wrong)
INSERT INTO AUDIT.PIPELINE_RUN (RUN_ID, STEP, STARTED_AT, FINISHED_AT, ROWS_OUT, RULE_VERSION, STATUS, NOTES)
SELECT UUID_STRING(), '02_raw',
       (SELECT MIN(_LOADED_AT) FROM RAW.CHARITIES_ORGANISATIONS),
       CURRENT_TIMESTAMP()::TIMESTAMP_NTZ,
       c.n, 'raw_v1',
       IFF(c.n = 46045 AND co.n = 2000 AND d.n = 39115, 'SUCCESS', 'FAIL'),
       'charities=' || c.n || ', companies_office=' || co.n || ', ird_donee=' || d.n
FROM (SELECT COUNT(*) n FROM RAW.CHARITIES_ORGANISATIONS) c,
     (SELECT COUNT(*) n FROM RAW.COMPANIES_OFFICE) co,
     (SELECT COUNT(*) n FROM RAW.IRD_DONEE) d;

-- 5) Row-count checks (last, so this result is what you see in Snowsight)
SELECT 'CHARITIES' AS source, COUNT(*) AS actual_rows, 46045 AS expected_rows,
       IFF(COUNT(*) = 46045, 'PASS', 'FAIL') AS check_result FROM RAW.CHARITIES_ORGANISATIONS
UNION ALL
SELECT 'COMPANIES_OFFICE', COUNT(*), 2000, IFF(COUNT(*) = 2000, 'PASS', 'FAIL') FROM RAW.COMPANIES_OFFICE
UNION ALL
SELECT 'IRD_DONEE', COUNT(*), 39115, IFF(COUNT(*) = 39115, 'PASS', 'FAIL') FROM RAW.IRD_DONEE;
