USE ROLE ACCOUNTADMIN;
USE WAREHOUSE TEAM_WH;
USE DATABASE KENDRIX_ER;
USE SCHEMA RAW;

CREATE OR REPLACE STORAGE INTEGRATION KENDRIX_S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN =
        'arn:aws:iam::539247494905:role/kendrix-snowflake-team'
    STORAGE_ALLOWED_LOCATIONS =
        ('s3://kendrix-er-dev-539247494905/processed/');

DESC INTEGRATION KENDRIX_S3_INT;

CREATE OR REPLACE FILE FORMAT KENDRIX_CSV_FORMAT
    TYPE = CSV
    PARSE_HEADER = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL', 'null');

CREATE OR REPLACE STAGE KENDRIX_S3_STAGE
    STORAGE_INTEGRATION = KENDRIX_S3_INT
    URL = 's3://kendrix-er-dev-539247494905/processed/'
    FILE_FORMAT = KENDRIX_CSV_FORMAT;

LIST @KENDRIX_S3_STAGE;